window.PROJECT_FLOW_SUPABASE_URL = "https://YOUR_PROJECT.supabase.co";
window.PROJECT_FLOW_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY";
window.PROJECT_FLOW_SUPPORT_EMAIL = "postmaster@pmpro.com.cn";
